#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LINKQ_BANCO
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BancoBD")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::LINKQ_BANCO.Properties.Settings.Default.BancoBDConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SPConsultaCuenta")]
		public ISingleResult<SPConsultaCuentaResult> SPConsultaCuenta([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCuenta", DbType="VarChar(5)")] string idCuenta)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCuenta);
			return ((ISingleResult<SPConsultaCuentaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SPEliminarCliente")]
		public int SPEliminarCliente([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCliente", DbType="VarChar(5)")] string idCliente)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCliente);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SPInsertarCliente")]
		public int SPInsertarCliente([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string idcliente, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string apellidos, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string nombre)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idcliente, apellidos, nombre);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SPModificarCliente")]
		public int SPModificarCliente([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string idCliente, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string apellidos, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string nombre)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCliente, apellidos, nombre);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SPListar")]
		public ISingleResult<SPListarResult> SPListar()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SPListarResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SPBuscarporApellido")]
		public ISingleResult<SPBuscarporApellidoResult> SPBuscarporApellido([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string apellido)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), apellido);
			return ((ISingleResult<SPBuscarporApellidoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SPBuscarporId")]
		public ISingleResult<SPBuscarporIdResult> SPBuscarporId([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<SPBuscarporIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SPBuscarporNombre")]
		public ISingleResult<SPBuscarporNombreResult> SPBuscarporNombre([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string nombre)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre);
			return ((ISingleResult<SPBuscarporNombreResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SPDevolverID")]
		public ISingleResult<SPDevolverIDResult> SPDevolverID([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string cliente)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cliente);
			return ((ISingleResult<SPDevolverIDResult>)(result.ReturnValue));
		}
	}
	
	public partial class SPConsultaCuentaResult
	{
		
		private string _IdCliente;
		
		private string _Apellidos;
		
		private string _Nombres;
		
		private string _IdCuenta;
		
		private string _IdCliente1;
		
		private System.Nullable<double> _Saldo;
		
		private string _Divisa;
		
		private string _IdMovimiento;
		
		private string _Idcuenta1;
		
		private string _Tipo;
		
		private System.Nullable<double> _Monto;
		
		private System.Nullable<System.DateTime> _Fecha;
		
		public SPConsultaCuentaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCliente", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string IdCliente
		{
			get
			{
				return this._IdCliente;
			}
			set
			{
				if ((this._IdCliente != value))
				{
					this._IdCliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellidos", DbType="VarChar(30)")]
		public string Apellidos
		{
			get
			{
				return this._Apellidos;
			}
			set
			{
				if ((this._Apellidos != value))
				{
					this._Apellidos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombres", DbType="VarChar(30)")]
		public string Nombres
		{
			get
			{
				return this._Nombres;
			}
			set
			{
				if ((this._Nombres != value))
				{
					this._Nombres = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCuenta", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string IdCuenta
		{
			get
			{
				return this._IdCuenta;
			}
			set
			{
				if ((this._IdCuenta != value))
				{
					this._IdCuenta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCliente1", DbType="VarChar(5)")]
		public string IdCliente1
		{
			get
			{
				return this._IdCliente1;
			}
			set
			{
				if ((this._IdCliente1 != value))
				{
					this._IdCliente1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Saldo", DbType="Float")]
		public System.Nullable<double> Saldo
		{
			get
			{
				return this._Saldo;
			}
			set
			{
				if ((this._Saldo != value))
				{
					this._Saldo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Divisa", DbType="VarChar(20)")]
		public string Divisa
		{
			get
			{
				return this._Divisa;
			}
			set
			{
				if ((this._Divisa != value))
				{
					this._Divisa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMovimiento", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string IdMovimiento
		{
			get
			{
				return this._IdMovimiento;
			}
			set
			{
				if ((this._IdMovimiento != value))
				{
					this._IdMovimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Idcuenta1", DbType="VarChar(5)")]
		public string Idcuenta1
		{
			get
			{
				return this._Idcuenta1;
			}
			set
			{
				if ((this._Idcuenta1 != value))
				{
					this._Idcuenta1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="VarChar(20)")]
		public string Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this._Tipo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Monto", DbType="Float")]
		public System.Nullable<double> Monto
		{
			get
			{
				return this._Monto;
			}
			set
			{
				if ((this._Monto != value))
				{
					this._Monto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="Date")]
		public System.Nullable<System.DateTime> Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this._Fecha = value;
				}
			}
		}
	}
	
	public partial class SPListarResult
	{
		
		private string _IdCliente;
		
		private string _Apellidos;
		
		private string _Nombres;
		
		public SPListarResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCliente", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string IdCliente
		{
			get
			{
				return this._IdCliente;
			}
			set
			{
				if ((this._IdCliente != value))
				{
					this._IdCliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellidos", DbType="VarChar(30)")]
		public string Apellidos
		{
			get
			{
				return this._Apellidos;
			}
			set
			{
				if ((this._Apellidos != value))
				{
					this._Apellidos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombres", DbType="VarChar(30)")]
		public string Nombres
		{
			get
			{
				return this._Nombres;
			}
			set
			{
				if ((this._Nombres != value))
				{
					this._Nombres = value;
				}
			}
		}
	}
	
	public partial class SPBuscarporApellidoResult
	{
		
		private string _IdCliente;
		
		private string _Apellidos;
		
		private string _Nombres;
		
		public SPBuscarporApellidoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCliente", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string IdCliente
		{
			get
			{
				return this._IdCliente;
			}
			set
			{
				if ((this._IdCliente != value))
				{
					this._IdCliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellidos", DbType="VarChar(30)")]
		public string Apellidos
		{
			get
			{
				return this._Apellidos;
			}
			set
			{
				if ((this._Apellidos != value))
				{
					this._Apellidos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombres", DbType="VarChar(30)")]
		public string Nombres
		{
			get
			{
				return this._Nombres;
			}
			set
			{
				if ((this._Nombres != value))
				{
					this._Nombres = value;
				}
			}
		}
	}
	
	public partial class SPBuscarporIdResult
	{
		
		private string _IdCliente;
		
		private string _Apellidos;
		
		private string _Nombres;
		
		public SPBuscarporIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCliente", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string IdCliente
		{
			get
			{
				return this._IdCliente;
			}
			set
			{
				if ((this._IdCliente != value))
				{
					this._IdCliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellidos", DbType="VarChar(30)")]
		public string Apellidos
		{
			get
			{
				return this._Apellidos;
			}
			set
			{
				if ((this._Apellidos != value))
				{
					this._Apellidos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombres", DbType="VarChar(30)")]
		public string Nombres
		{
			get
			{
				return this._Nombres;
			}
			set
			{
				if ((this._Nombres != value))
				{
					this._Nombres = value;
				}
			}
		}
	}
	
	public partial class SPBuscarporNombreResult
	{
		
		private string _IdCliente;
		
		private string _Apellidos;
		
		private string _Nombres;
		
		public SPBuscarporNombreResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCliente", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string IdCliente
		{
			get
			{
				return this._IdCliente;
			}
			set
			{
				if ((this._IdCliente != value))
				{
					this._IdCliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellidos", DbType="VarChar(30)")]
		public string Apellidos
		{
			get
			{
				return this._Apellidos;
			}
			set
			{
				if ((this._Apellidos != value))
				{
					this._Apellidos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombres", DbType="VarChar(30)")]
		public string Nombres
		{
			get
			{
				return this._Nombres;
			}
			set
			{
				if ((this._Nombres != value))
				{
					this._Nombres = value;
				}
			}
		}
	}
	
	public partial class SPDevolverIDResult
	{
		
		private string _Idcliente;
		
		public SPDevolverIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Idcliente", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string Idcliente
		{
			get
			{
				return this._Idcliente;
			}
			set
			{
				if ((this._Idcliente != value))
				{
					this._Idcliente = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
