//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelfirst2
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLEADO()
        {
            this.REGISTRO_TRANSACCIN_DEDUCCION = new HashSet<REGISTRO_TRANSACCIN_DEDUCCION>();
            this.REGISTRO_TRANSACCION = new HashSet<REGISTRO_TRANSACCION>();
        }
    
        public int Id_Empleado { get; set; }
        public string Cod_Empleado { get; set; }
        public string Nombre_Empleado { get; set; }
        public int Id_Departamento { get; set; }
        public int Id_Puesto { get; set; }
        public double Salario_Mensual_Emplea { get; set; }
        public string Cedula_Empleado { get; set; }
        public string Responsable_Area { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGISTRO_TRANSACCIN_DEDUCCION> REGISTRO_TRANSACCIN_DEDUCCION { get; set; }
        public virtual PUESTO PUESTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGISTRO_TRANSACCION> REGISTRO_TRANSACCION { get; set; }
        public virtual DEPARTAMENTO DEPARTAMENTO { get; set; }
    }
}
