//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelfirst2
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTRO_TRANSACCIN_DEDUCCION
    {
        public int Id_Transaccion_Deduccion { get; set; }
        public int Id_Empleado { get; set; }
        public int Id_Tipo_Deduccion { get; set; }
        public System.DateTime Fecha { get; set; }
        public double Monto { get; set; }
    
        public virtual TIPO_DE_DEDUCCION TIPO_DE_DEDUCCION { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
    }
}
