//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelfirst2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_DE_INGRESO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPO_DE_INGRESO()
        {
            this.REGISTRO_TRANSACCION = new HashSet<REGISTRO_TRANSACCION>();
        }
    
        public int Id_Tipo_Ingreso { get; set; }
        public string Nombre_Tipo_Deduccion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGISTRO_TRANSACCION> REGISTRO_TRANSACCION { get; set; }
    }
}
